"""
Unit tests for ingestion, LangGraph nodes, and the core CAG pipeline.
"""
from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from cag.agents.models import RankedChunk, ReasoningOutput, RetrievalOutput
from cag.graph.nodes import (
    entry_node,
    exit_node,
    reason_node,
    refine_node,
    retrieve_node,
    route_after_refine,
    route_after_validate,
    validate_node,
)
from cag.graph.state import CAGState


@pytest.fixture
def base_state() -> CAGState:
    return {
        "query": "What prerequisites are required before using the onboarding workflow?",
        "question_scope": "domain",
        "retrieval_strategy": "semantic",
        "chunks": [],
        "ranked_chunks": [],
        "gaps": [],
        "relevance_score": 0.0,
        "answer": "",
        "confidence": 0.0,
        "citations": [],
        "hallucination_risk": 0.0,
        "query_type": "GENERAL",
        "should_escalate": False,
        "reason_retries": 0,
        "error_message": "",
        "node_trace": [],
        "conversation_history": [],
    }


@pytest.fixture
def mock_retrieval_output() -> RetrievalOutput:
    return RetrievalOutput(
        chunks_ranked=[
            RankedChunk(
                content="The workflow requires an active project, assigned owner, and notification rules.",
                source="team_handbook_setup.txt",
                domain_module="workflow",
                relevance_score=0.92,
                relevance_reason="Direct coverage of workflow prerequisites.",
            )
        ],
        gaps=[],
        relevance_score=0.92,
        summary="Relevant setup guidance found.",
    )


@pytest.fixture
def mock_reasoning_output() -> ReasoningOutput:
    from cag.agents.models import Citation

    return ReasoningOutput(
        answer="To configure the workflow, ensure the project is active, assign an owner, and set notification rules.",
        query_type="CONFIGURATION",
        confidence=0.88,
        citations=[
            Citation(
                text="The workflow requires an active project, assigned owner, and notification rules.",
                source="team_handbook_setup.txt",
                domain_module="workflow",
            )
        ],
        hallucination_risk=0.08,
        hallucination_reason="Answer is based directly on the retrieved evidence.",
    )


class TestEntryNode:
    def test_classifies_diagnostic_questions(self, base_state):
        state = {**base_state, "query": "Error 404 in the asset register"}
        result = entry_node(state)
        assert result["query_type"] == "DIAGNOSTIC"
        assert "ENTRY" in result["node_trace"]

    def test_classifies_diagnostic_questions_with_why(self, base_state):
        state = {**base_state, "query": "Why is the export rejected by the system?"}
        result = entry_node(state)
        assert result["query_type"] == "DIAGNOSTIC"

    def test_classifies_configuration_questions(self, base_state):
        state = {**base_state, "query": "Which fields are required to configure the workflow?"}
        result = entry_node(state)
        assert result["query_type"] == "CONFIGURATION"
        assert result["retrieval_strategy"] == "semantic"

    def test_classifies_prerequisites_as_configuration(self, base_state):
        state = {**base_state, "query": "What prerequisites must be completed before using the workflow?"}
        result = entry_node(state)
        assert result["query_type"] == "CONFIGURATION"

    def test_classifies_procedural_questions(self, base_state):
        state = {**base_state, "query": "How do I complete the year-end workflow?"}
        result = entry_node(state)
        assert result["query_type"] == "PROCEDURAL"

    def test_classifies_general_questions(self, base_state):
        state = {**base_state, "query": "Which reports are generated by the workflow?"}
        result = entry_node(state)
        assert result["query_type"] == "GENERAL"

    def test_classifies_workflow_questions_as_procedural(self, base_state):
        state = {**base_state, "query": "Describe the workflow step by step for new employee onboarding."}
        result = entry_node(state)
        assert result["query_type"] == "PROCEDURAL"

    def test_adds_query_to_conversation_history(self, base_state):
        result = entry_node(base_state)
        assert len(result["conversation_history"]) == 1

    def test_resets_runtime_fields(self, base_state):
        result = entry_node(base_state)
        assert result["chunks"] == []
        assert result["answer"] == ""
        assert result["should_escalate"] is False


class TestRetrieveNode:
    def test_recovers_chunks_from_vector_store(self, base_state):
        mock_doc = MagicMock()
        mock_doc.page_content = "Workflow setup content"
        mock_doc.metadata = {"filename": "team_handbook_setup.txt", "domain_module": "workflow", "chunk_index": 0}

        with patch("cag.graph.nodes.similarity_search", return_value=[mock_doc]):
            result = retrieve_node(base_state)

        assert len(result["chunks"]) == 1
        assert result["chunks"][0]["content"] == "Workflow setup content"
        assert result["chunks"][0]["domain_module"] == "workflow"
        assert "RETRIEVE" in result["node_trace"]

    def test_handles_vector_store_errors(self, base_state):
        with patch("cag.graph.nodes.similarity_search", side_effect=Exception("Vector store unavailable")):
            result = retrieve_node(base_state)

        assert result["chunks"] == []
        assert "RETRIEVE" in result["node_trace"]


class TestRefineNode:
    def test_ranks_chunks(self, base_state, mock_retrieval_output):
        state = {**base_state, "chunks": [{"content": "Workflow docs"}], "node_trace": ["ENTRY", "RETRIEVE"]}

        with patch("cag.graph.nodes.run_retrieval_agent", return_value=mock_retrieval_output):
            result = refine_node(state)

        assert result["relevance_score"] == 0.92
        assert len(result["ranked_chunks"]) == 1
        assert result["ranked_chunks"][0]["domain_module"] == "workflow"
        assert "REFINE" in result["node_trace"]


class TestReasonNode:
    def test_generates_an_answer(self, base_state, mock_reasoning_output):
        state = {
            **base_state,
            "ranked_chunks": [{"content": "Workflow docs", "relevance_score": 0.92}],
            "gaps": [],
            "node_trace": ["ENTRY", "RETRIEVE", "REFINE"],
        }

        with patch("cag.graph.nodes.run_reasoning_agent", return_value=mock_reasoning_output):
            result = reason_node(state)

        assert "workflow" in result["answer"].lower()
        assert result["confidence"] == 0.88
        assert result["hallucination_risk"] == 0.08
        assert result["reason_retries"] == 1

    def test_preserves_graph_inferred_query_type(self, base_state, mock_reasoning_output):
        state = {
            **base_state,
            "query_type": "PROCEDURAL",
            "ranked_chunks": [{"content": "Workflow docs", "relevance_score": 0.92}],
            "gaps": [],
            "node_trace": ["ENTRY", "RETRIEVE", "REFINE"],
        }

        with patch("cag.graph.nodes.run_reasoning_agent", return_value=mock_reasoning_output):
            result = reason_node(state)

        assert result["query_type"] == "PROCEDURAL"


class TestValidateNode:
    def test_accepts_supported_answers(self, base_state):
        state = {
            **base_state,
            "answer": "A supported answer based on the documentation.",
            "hallucination_risk": 0.05,
            "confidence": 0.88,
            "relevance_score": 0.92,
            "ranked_chunks": [{"content": "chunk", "relevance_score": 0.92}],
            "reason_retries": 1,
        }
        result = validate_node(state)
        assert result["should_escalate"] is False

    def test_escalates_after_high_hallucination_and_max_retries(self, base_state):
        state = {
            **base_state,
            "answer": "Uncertain answer with insufficient coverage.",
            "hallucination_risk": 0.8,
            "confidence": 0.3,
            "relevance_score": 0.9,
            "ranked_chunks": [{"content": "chunk", "relevance_score": 0.9}],
            "reason_retries": 3,
        }
        result = validate_node(state)
        assert result["should_escalate"] is True
        assert "hallucination" in result["error_message"].lower()

    def test_escalates_for_low_relevance(self, base_state):
        state = {**base_state, "relevance_score": 0.1, "ranked_chunks": [], "reason_retries": 0}
        result = validate_node(state)
        assert result["should_escalate"] is True

    def test_escalates_when_the_answer_declares_insufficient_coverage(self, base_state):
        state = {
            **base_state,
            "answer": "The documentation available does not cover this request reliably.",
            "ranked_chunks": [{"content": "chunk", "relevance_score": 0.4}],
            "relevance_score": 0.4,
            "reason_retries": 1,
        }
        result = validate_node(state)
        assert result["should_escalate"] is True

    def test_does_not_escalate_for_a_cautious_but_supported_answer(self, base_state):
        state = {
            **base_state,
            "answer": "The documentation covers the main reports, but does not detail minor exceptions.",
            "ranked_chunks": [{"content": "chunk", "relevance_score": 0.82}],
            "relevance_score": 0.82,
            "confidence": 0.9,
            "hallucination_risk": 0.1,
            "reason_retries": 1,
        }
        result = validate_node(state)
        assert result["should_escalate"] is False


class TestRouting:
    def test_route_after_refine_with_high_relevance(self, base_state):
        state = {
            **base_state,
            "relevance_score": 0.9,
            "ranked_chunks": [{"content": "chunk", "relevance_score": 0.9}],
        }
        assert route_after_refine(state) == "reason"

    def test_route_after_refine_with_low_relevance(self, base_state):
        state = {**base_state, "relevance_score": 0.2, "ranked_chunks": []}
        assert route_after_refine(state) == "validate"

    def test_route_after_validate_ok(self, base_state):
        state = {**base_state, "should_escalate": False, "hallucination_risk": 0.05, "reason_retries": 1}
        assert route_after_validate(state) == "exit"

    def test_route_after_validate_escalation(self, base_state):
        state = {**base_state, "should_escalate": True}
        assert route_after_validate(state) == "exit"

    def test_route_after_validate_retry(self, base_state):
        state = {**base_state, "should_escalate": False, "hallucination_risk": 0.6, "reason_retries": 1}
        assert route_after_validate(state) == "reason"


class TestExitNode:
    def test_returns_normal_answer(self, base_state):
        state = {**base_state, "answer": "Configuration completed.", "should_escalate": False}
        result = exit_node(state)
        assert result["answer"] == "Configuration completed."

    def test_returns_escalation_message(self, base_state):
        state = {**base_state, "should_escalate": True, "error_message": "Documentation is insufficient."}
        result = exit_node(state)
        assert "human" in result["answer"].lower()


class TestIngestion:
    def test_chunker_splits_long_documents(self):
        from langchain_core.documents import Document

        from cag.ingestion.chunker import chunk_documents

        long_text = "Test paragraph. " * 200
        docs = [Document(page_content=long_text, metadata={"filename": "test.txt", "source": "test"})]
        chunks = chunk_documents(docs)
        assert len(chunks) > 1

    def test_chunker_preserves_metadata(self):
        from langchain_core.documents import Document

        from cag.ingestion.chunker import chunk_documents

        docs = [Document(page_content="Short text.", metadata={"filename": "x.txt", "domain_module": "workflow"})]
        chunks = chunk_documents(docs)
        assert chunks[0].metadata["domain_module"] == "workflow"
        assert "chunk_index" in chunks[0].metadata

    def test_loader_extracts_domain_module(self):
        from cag.ingestion.loader import _extract_domain_module

        assert _extract_domain_module("manual_onboarding_workflow") == "onboarding"
        assert _extract_domain_module("guide_asset_register_policy") == "asset"
        assert _extract_domain_module("team_documentation") == "team"
